name: Gold
favicon: null
layout_spectrum: 0.21714
typography_spectrum: 0.37551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1ad8b'
    - '#000000'
    - '#3d4046'
    - '#77594b'
    - '#997764'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
